### ISSUE TITLE
Support munit 1.0.0?

### ISSUE THREAD

**Issue by guizmaii** [poslegm/munit-zio#153]
When I execute my tests suite, I have the following error:
```
==> X zio.uuid.GeneratorSuite.initializationError  0.001s java.lang.NoSuchMethodError: 'void munit.ValueTransforms$ValueTransform.<init>(munit.FunSuite, java.lang.String, scala.PartialFunction)'
    at munit.ZSuite.<init>(ZSuite.scala:47)
    at zio.uuid.GeneratorSuite.<init>(GeneratorSuite.scala:25)
```

See: 
- https://github.com/guizmaii-opensource/zio-uuid/actions/runs/9915677836/job/27396917270?pr=55
- https://github.com/guizmaii-opensource/zio-uuid/pull/55

**Comment by poslegm** [comment]
@guizmaii Hello!
Sorry for the delay. [Released](https://mvnrepository.com/artifact/com.github.poslegm/munit-zio_3/0.3.0) v0.3.0 with latest munit and zio versions.

**Comment by guizmaii** [comment]
Thanks @poslegm 🙏
