### ISSUE TITLE
java.lang.NoSuchMethodError on suite run

### ISSUE THREAD

**Issue by amricko0b** [poslegm/munit-zio#61]
Greetings!

I'm trying to integrate munit-zio into my project, but the very first simple test suite failed with uknown runtime error.

Code to reproduce:
```
import munit.ZSuite
import zio._

class ConfigSuite extends ZSuite {

  testZ("Just add two numbers") {
    assertEqualsZ(ZIO.succeed(1 + 3), 4)
  }
}
```

It compiles, but fails with `java.lang.NoSuchMethodError: 'zio.Runtime zio.Runtime$.global()'`.

I'm using zio `v2.0.0` and munit-zio `v0.0.3`.

Could you please help me to understand what I did wrong?

**Comment by poslegm** [comment]
Hello! Version 0.0.3 does not support ZIO 2.0. 

I created PR with update, new version coming soon.

**Comment by amricko0b** [comment]
Oh, my bad...
I should have looked at dependecies definition before opening this issue.
Thank for your help!
